### ISSUE TITLE
Requirements for Basic science fuild 2 are inconsistent

### ISSUE THREAD

**Issue by karv** [LovelySanta/FactorioMod-MoreScience-BobAngelsExtension#1]
To build Basic science fluid 2 it is needed Express Inserters which is unlocked by Logistics 3, a much more advanced science that require Basic science fluid 2 to unlock.

I have Bob + MoreScience + MoreScience-BobAngelsExtension loaded (not Angel).  
Is Angel mod necessary?

**Comment by LovelySanta** [comment]
Hi,

I just checked: I got the latest version of my more science base mod and bobangels extension, and also downloaded all the bobs mod (I guess you're playing with all the bob parts?).

To clear things up: It is NOT needed to play with all bobs or angels parts, you can add the parts you like, leave other parts out of it.

On this topic again: Ingame it looks for me like this:
![Screenshot of recipe of basic science fluid 2](https://i.imgur.com/ygfNrZR.png)
As you can see it requires __Fast inserters__ and not the __Express inserters__. The fast inserters are unlocked by the research called __Logistics__ (and require only basic science pack 1).

Just to be sure, can you double check this in your game? If it does require express inserters, can you post a screenshot and upload a zip file with your mods?

Kind regards,
lovely_santa

**Comment by LovelySanta** [comment]
Same bugreport [on the mod portal](https://mods.factorio.com/mod/MoreScience/discussion/5b3a8ce4ef5d2d000ad52402), with that new information this will more likely be a bug becose of the settings. I'll look more into that.
