### ISSUE TITLE
cycle in tree detected

### ISSUE THREAD

**Issue by vigonz06** [LovelySanta/FactorioMod-MoreScience-BobAngelsExtension#11]
when installing this mod(https://mods.factorio.com/mod/AngelBob_Better_Concrete), once you restart the game, it detects a cycle in the tech tree

angels-stone-smelting-2
>angels-stone-smelting-2

I tell this to you because it doesnt happen without this mod.

**Comment by LovelySanta** [comment]
I'll look at it and see what I can do.

For own reference [original post](https://mods.factorio.com/mod/AngelBob_Better_Concrete/discussion/5d4feaa9a36f03000cf33b1c).

Kind regards
lovely_santa

**Comment by LovelySanta** [comment]
I found a quick fix for this, but for reasoning it's beter that he changes it on his end. Here is my reply I gave him:

> Ok, I figured it out...
> In MS, i'm depending "angels-stone-smelting-2" on "concrete", what is fairly normal for when you play regular bobs angels, as "concrete" is the first tech version, and "angels-stone-smelting-2" extends on this.
> 
> ```lua
> LSlib.technology.addPrerequisite("angels-stone-smelting-2", "concrete")
> ```
> 
> So, when your mods load then, you swap out the "concrete" dependency for "angels-stone-smelting-2".
> 
> ```lua
> for _, tech in pairs(data.raw.technology) do
>     if tech.prerequisites then
>         bobmods.lib.tech.replace_prerequisite(tech.name, "concrete", "angels-stone-smelting-2")
>     end
> end
> ```
> 
> I can easly fix this by just not adding that dependency when your mod is present
> 
> ```lua
>   if not mods["AngelBob_Better_Concrete"] then
>     LSlib.technology.addPrerequisite("angels-stone-smelting-2", "concrete")
>   end
> ```
> 
> But I rather have that you fix it in your mod as follows (since your mod is altering the concrete, and > making these mayor changes):
> 
> ```lua
> for _, tech in pairs(data.raw.technology) do
>     if tech.name == "angels-stone-smelting-2" then
>         bobmods.lib.tech.remove_prerequisite(tech.name, "concrete")
>     elseif tech.prerequisites then
>         bobmods.lib.tech.replace_prerequisite(tech.name, "concrete", "angels-stone-smelting-2")
>     end
> end
> ```
> 
> So this will prevent you from depending in the angels stone smelting itself..., which in the end will > add compatibility to all mods that add "concrete" as a dependency to "angels-stone-smelting-2".
> 
> I've put this code in your mod (from version 0.17.1, without any mod compatibility) and it loads correctly, and keeps the technology and your mod changes intact:
> ![](https://www.mupload.nl/img/p7qh4ds.png)

I'll mark this as resolved for now.

Kind regards
lovely_santa

**Comment by vigonz06** [comment]
yes, I saw it in the thread, thanks
