### ISSUE TITLE
some technologies unresearchable

### ISSUE THREAD

**Issue by vigonz06** [LovelySanta/FactorioMod-MoreScience-BobAngelsExtension#12]
![Captura](https://user-images.githubusercontent.com/9486307/62841125-c8246e80-bca4-11e9-8b00-4bdce68145c0.PNG)

all those techs cannot be researched when your mods are present (actually not sure wich mod causes the problema, can be this one, or more science)

![Captura2](https://user-images.githubusercontent.com/9486307/62841210-703a3780-bca5-11e9-9718-a47a239c3a3c.PNG)

this second picture is from my tech tree with your mods installed, as you can see, in the first picture, in the bottom left corner there is the tunsten alloys research, wich is abailable, and in the second, the same tech has its prerequisite investigated, but it cannot be researched

**Comment by vigonz06** [comment]
I'm really sorry to bother you so much

**Comment by vigonz06** [comment]
apparently the problematic techs are battery and tungsten alloys. I researches those two without your mods, then installed them back, and I could research every other tech, having your mods

**Comment by vigonz06** [comment]
apparently, nitinol processing cannot be researched either

**Comment by vigonz06** [comment]
advanced logistic science pack
nitinol processing
tungsten alloys
battery

those were the four techs I had to investigate without your mods

**Comment by LovelySanta** [comment]
Can you provide a save file so I can sync my mod list?

**Comment by vigonz06** [comment]
https://github.com/vigonz06/nuevos_comienzos

that's my repo for the save game, the .zip file
you also have the mod-list file

**Comment by vigonz06** [comment]
save game*

**Comment by vigonz06** [comment]
all I did between the first and the second pictures was reactivate your library (so, all three of your mods)

**Comment by LovelySanta** [comment]
The issue is in the "bobs furnaces are multi-purpose" mod disables the `alloy-processing-2` technology. This is the technology that is not visible in the tech tree, that is present in bobs angels mods, preventing you from researching the alloy processing.

So since that mod is messing with bobs mods, it's his task to fix the technologies that depend on the one he disables... Nothing I can do about it sadly. You should report it to him.

Kind regards
lovely_santa

**Comment by vigonz06** [comment]
I see, thanks

**Comment by vigonz06** [comment]
still cannot research battery, and has nothing to do with multy-purpouses furnaces, I checked, again, I disable your mods and I can research it

**Comment by vigonz06** [comment]
and advanced logistic science pack, unresearchable too, with your mods

**Comment by LovelySanta** [comment]
same reason.. there are mods that alter the tech tree such as more bobs in this case... I'll add more mod compatibility when I got more time...
