### ISSUE TITLE
Circular Dependency (Factorio 0.17.36, MoSci 0.2.5, Bob's elect. 0.17.4, Bob's tech 0.17.3, Bob's plates 0.17.4, this mod 0.2.0)

### ISSUE THREAD

**Issue by computerneek** [LovelySanta/FactorioMod-MoreScience-BobAngelsExtension#7]
![Capture](https://user-images.githubusercontent.com/17407799/57257076-5e058900-7026-11e9-8697-ae1a7b577809.PNG)
That's the problem- an issue with the compatibilities this mod makes.  It goes as thus:

To make a basic electronic board, you need to make solder.
To make that, you have to make a metal mixing furnace.
Thanks to this mod, _Alloy processing 1_, the research the metal mixing furnace is unlocked by, requires the Transport science pack as well as the Automation science pack.  (It's just science 1 with only Bob's tech).
The transport science pack is made with basic belts and inserters- no biggie.  BUT, it's one we can't make directly.  We have to make it the fluid way.  We need purified water.
To get purified water (and convert it into science fluids), we have to build a chemical plant.
A chemical plant is built with five basic electronic boards.
Which brings us back to the beginning.  To make a basic electronic board, you need solder.

Unfortunately, this loop makes any world with this combination of mods unplayable, even though this mod is _specifically_ compatible with every other relevant mod on the list.  (I do have other mods on the world, but none of them are related)

It would make sense to me to simply drop the transport science pack off the _Alloy processing 1_ research, thus breaking this loop and enabling basic circuits to be achieved without cheating.  The only other thing this research allows is bronze production, and its use in pipes.  Bronze, an alloy of copper and tin, doesn't reach any further than steel (on underground pipes), making it utterly useless without one or more of the follow-up researches...  which can be made more expensive, if desired, to compensate for the loss in price of 30 transport science packs.

**Comment by LovelySanta** [comment]
Yes, I am aware of this loop, it is intended that it is only red science. As you describe, it requires green science as of now, which is not intended. I'll fix this tomorrow.

Kind regards
lovely_santa

**Comment by LovelySanta** [comment]
I've split the `Alloy processing 1` technology into two pieces. The technology `Alloy processing 1` remains the same, but I removed the stone metal mixing furnace unlock from it. This furnace is now unlocked on its own in a new technology `Metal mixing furnace 1` that only requires red science.

Now the `Metal mixing furnace 1` is a prerequisite for the `Electronics` technology, and now you are able to create the solder recipe and finaly create the circuits. This is released in v0.2.2.

Kind regards
lovely_santa
