### ISSUE TITLE
mod messes with ReStack

### ISSUE THREAD

**Issue by vigonz06** [LovelySanta/FactorioMod-MoreScience-BobAngelsExtension#8]
I dont know if its this mod or more science, but it says that ReStack table index is nil

**Comment by vigonz06** [comment]
for some reason, this mode also removes sand, messing with AAI industry, and angle smelting extended

**Comment by LovelySanta** [comment]
If you post a picture  of the error (you can take a screenshot and paste it directly into here), I can tell you which mod the error comes from. But I don't think it is mine causing the error.

I don't have mod compatibility with AAI (yet, planned, no timeline), and I could look into angels smelting extended if I can get mod compatibility in there.

**Comment by vigonz06** [comment]
![Captura](https://user-images.githubusercontent.com/9486307/62159054-25b5d400-b311-11e9-9b41-49f8efbf0e1e.PNG)

**Comment by vigonz06** [comment]
this only happens with the two more science mods, plus your library. I have many more mods, but none of them cause this

**Comment by LovelySanta** [comment]
It has nothing to do with my mod, you should report this error to the ReStack mod as it is in his `data-final-fixes.lua` file (line 31) that the error is happening. Nothing I can do about that...

I've messaged Optera (the mod author) on discord to notify him about this, and I made a bug report on his github page (reference below)

**Comment by vigonz06** [comment]
did that, thanks

**Comment by LovelySanta** [comment]
I've provided as much info as I can, i'll close this issue as there is nothing more I can do...

**Comment by 0ptera** [comment]
You set an table with key instead of the returned item.name.
When I serpent.dump your launch product I see this:
```
   7.900 Script @__ReStack__/data-final-fixes.lua:31: [RS] launch product: do local _={"rocketpart-payload-mk1[space-science-pack]",1};return _;end
```

Correctly done launch products look like this:
```
 6.897 Script @__ReStack__/data-final-fixes.lua:31: [RS] launch product: do local _={"space-science-pack",1000};return _;end
```

**Comment by LovelySanta** [comment]
I got an item that is called `"rocketpart-payload-mk1[space-science-pack]"` and the amount returning is 1, so this is a valid launch product, it is not a table with a key, it is a string...

![image](https://user-images.githubusercontent.com/26593477/62191521-ed93ad00-b373-11e9-897e-c8f9c26777a9.png)

**Comment by 0ptera** [comment]
Confusing naming choice. I wouldn't use special characters like brackets in name strings even if the compiler can handle that.

On another note, ReStack works fine with that launch product for me.

Update: I missed launch products and that launch product can have either indexed table or  named keys. ReStack should handle either fine with 0.5.5.
