### ISSUE TITLE
no sand

### ISSUE THREAD

**Issue by vigonz06** [LovelySanta/FactorioMod-MoreScience-BobAngelsExtension#9]
Hi, I know I already said something about this, the mod removes sand, making it incompatible with some other mods, like AAI industry and rocket silo construction. You said that you didnt make this compatible with any of those, but thats not the problem I think, its not about AAI not using your aditional science, is about sand vanishing, could you check why sand disapears?

**Comment by LovelySanta** [comment]
I create a `sand` item in the MoreScience base mod. This is obtained by purifying water and smelted into glass.
when angels smelting mod is present (and that one requires refining), I use the `solid-sand` from angel instead... There is always a sand item, as I require sand in my to make glass for the bottles, and if angel is present I use his sand/glass instead.

Here is the code:
https://github.com/LovelySanta/FactorioMod-MoreScience-BobAngelsExtension/blob/3a87d5343c621b1fa55b1d4b7ee9d54c088bfe68/prototypes/angelsrefining/data.lua#L98-L120

I hope this answers your question?

**Comment by vigonz06** [comment]
What is that solid-sand item? I mean, angel smelting doesnt have any problems with any sand mods, why yours do?

**Comment by vigonz06** [comment]
Anyway, maybe I should ask AAI modder to add conpatibility with your mod, idk

**Comment by LovelySanta** [comment]
the solid sand is angels sand from water washing... and feel free to ask AAI

**Comment by vigonz06** [comment]
> the solid sand is angels sand from water washing... 

ok, so, washed sand, there is already a compatibility between AAI and Angels, where you can get washed sand from AAI sand + water, so... why is it necesary for your mods to remove common sand?

**Comment by LovelySanta** [comment]
I introduced sand in my initial mod (More Science), and when it is used together with angels, I don't require my sand anymore, so I remove it again... If I kept it in there, there would be no reason to use angels smelting to obtain glass.... And that would mess up the whole silicon chain...

**Comment by vigonz06** [comment]
as it is now, you can obtain glass from both sand and molten glass, but ok, guess I'll just uninstall all mods using sand

**Comment by vigonz06** [comment]
btw, you can also get glass with silicon ore, without smelting

**Comment by LovelySanta** [comment]
I am aware you can get glass with silicon ore, but thats just tier1, when (like i said) you used the sand that i introduced in the More Science mod, the whole silicon ore would become obsolete (except from when it's used as secundary ore in other smelting recipes)

**Comment by vigonz06** [comment]
oh, ok, I understand
